//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraderForPoe.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PLAYERNAME")]
        public string PlayerName {
            get {
                return ((string)(this["PlayerName"]));
            }
            set {
                this["PlayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool CollapsedItems {
            get {
                return ((bool)(this["CollapsedItems"]));
            }
            set {
                this["CollapsedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool PlayNotificationSound {
            get {
                return ((bool)(this["PlayNotificationSound"]));
            }
            set {
                this["PlayNotificationSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathToClientTxt {
            get {
                return ((string)(this["PathToClientTxt"]));
            }
            set {
                this["PathToClientTxt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Give me one second! :) (Sent with TraderForPoe)")]
        public string CustomWhisper1 {
            get {
                return ((string)(this["CustomWhisper1"]));
            }
            set {
                this["CustomWhisper1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseItemAfterCustomWhisper1 {
            get {
                return ((bool)(this["CloseItemAfterCustomWhisper1"]));
            }
            set {
                this["CloseItemAfterCustomWhisper1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Already sold, sorry. :( (Sent with TraderForPoe)")]
        public string CustomWhisper2 {
            get {
                return ((string)(this["CustomWhisper2"]));
            }
            set {
                this["CustomWhisper2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseItemAfterCustomWhisper2 {
            get {
                return ((bool)(this["CloseItemAfterCustomWhisper2"]));
            }
            set {
                this["CloseItemAfterCustomWhisper2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thank you very much, good luck and have a nice day. :) (Sent with TraderForPoe)")]
        public string ThankYouWhisper {
            get {
                return ((string)(this["ThankYouWhisper"]));
            }
            set {
                this["ThankYouWhisper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseItemAfterThankYouWhisper {
            get {
                return ((bool)(this["CloseItemAfterThankYouWhisper"]));
            }
            set {
                this["CloseItemAfterThankYouWhisper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hi, I\'m busy right now. Shall I write you after? :) (Sent with TraderForPoe)")]
        public string ImBusyWhisper {
            get {
                return ((string)(this["ImBusyWhisper"]));
            }
            set {
                this["ImBusyWhisper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseItemAfterImBusyWhisper {
            get {
                return ((bool)(this["CloseItemAfterImBusyWhisper"]));
            }
            set {
                this["CloseItemAfterImBusyWhisper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseClipboardMonitor {
            get {
                return ((bool)(this["UseClipboardMonitor"]));
            }
            set {
                this["UseClipboardMonitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CloseItemAfterTrade {
            get {
                return ((bool)(this["CloseItemAfterTrade"]));
            }
            set {
                this["CloseItemAfterTrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\"\r\n               xmlns:xsd=\"http://www.w3.org/2001/X" +
            "MLSchema\" />")]
        public global::System.Collections.ObjectModel.ObservableCollection<System.String> QuadStash {
            get {
                return ((global::System.Collections.ObjectModel.ObservableCollection<System.String>)(this["QuadStash"]));
            }
            set {
                this["QuadStash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeSettingsRequired {
            get {
                return ((bool)(this["UpgradeSettingsRequired"]));
            }
            set {
                this["UpgradeSettingsRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PosTop {
            get {
                return ((double)(this["PosTop"]));
            }
            set {
                this["PosTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PosLeft {
            get {
                return ((double)(this["PosLeft"]));
            }
            set {
                this["PosLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideIfPoeNotForeGround {
            get {
                return ((bool)(this["HideIfPoeNotForeGround"]));
            }
            set {
                this["HideIfPoeNotForeGround"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckForUpdatesOnStart {
            get {
                return ((bool)(this["CheckForUpdatesOnStart"]));
            }
            set {
                this["CheckForUpdatesOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int HistoryItemsCount {
            get {
                return ((int)(this["HistoryItemsCount"]));
            }
            set {
                this["HistoryItemsCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Item sold? :) (Sent with TraderForPoe)")]
        public string CustomWhisper3 {
            get {
                return ((string)(this["CustomWhisper3"]));
            }
            set {
                this["CustomWhisper3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I am in lab! :) (Sent with TraderForPoe)")]
        public string CustomWhisper4 {
            get {
                return ((string)(this["CustomWhisper4"]));
            }
            set {
                this["CustomWhisper4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseItemAfterCustomWhisper3 {
            get {
                return ((bool)(this["CloseItemAfterCustomWhisper3"]));
            }
            set {
                this["CloseItemAfterCustomWhisper3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseItemAfterCustomWhisper4 {
            get {
                return ((bool)(this["CloseItemAfterCustomWhisper4"]));
            }
            set {
                this["CloseItemAfterCustomWhisper4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float ControlOpacity {
            get {
                return ((float)(this["ControlOpacity"]));
            }
            set {
                this["ControlOpacity"] = value;
            }
        }
    }
}
